### ISSUE TITLE
`CUDA` extension introduces a circular dependency

### ISSUE THREAD

**Issue by fhagemann** [JuliaConcurrent/Atomix.jl#47]
The `CUDA` extension introduced in b027bdd610c78a78d40517050b6c349dfb0c3244 introduced a circular dependency,
as `CUDA` already depends on `Atomix` via `KernelAbstractions`.
```julia
]add CUDA
]why Atomix
```
```
CUDA → KernelAbstractions → Atomix
```

When loading Atomix with the prior commit 25d9da2, everything is fine:
```julia
]add Atomix#25d9da2
]add CUDA
```

When loading the newest version of Atomix, I get the following warning 
```julia
]add Atomix
]add CUDA
```
```
┌ Warning: Circular dependency detected. Precompilation will be skipped for:
│   Base.PkgId(Base.UUID("85068d23-b5fb-53f1-8204-05c2aba6942f"), "SparseArraysExt")
│   Base.PkgId(Base.UUID("13011619-4c7c-5ef0-948f-5fc81565cd05"), "AtomixCUDAExt")
│   Base.PkgId(Base.UUID("66d79d19-2cc4-5b0b-ac7a-b340256d1ecd"), "LinearAlgebraExt")
│   Base.PkgId(Base.UUID("63c18a36-062a-441e-b654-da1e3ab1ce7c"), "KernelAbstractions")
│   Base.PkgId(Base.UUID("052768ef-5323-5732-b1bb-66c8b64840ba"), "CUDA")
└ @ Base.Precompilation precompilation.jl:511
```

**Comment by christiangnrd** [comment]
This is not a real circular dependency and your code will probably still work. The warning will be gone in a few days with v1.11.2 and in the coming weeks with v1.10.8.

See https://github.com/JuliaConcurrent/Atomix.jl/issues/44
